use ecommerce;

#Supplier Table
create table if not exists `supplier`(
`SUPP_ID` int primary key,
`SUPP_NAME` varchar(50) NOT NULL,
`SUPP_CITY` varchar(50),
`SUPP_PHONE` varchar(10) NOT NULL
);

#customer tabale 
CREATE TABLE IF NOT EXISTS `customer` (
 `CUS_ID` INT NOT NULL PRIMARY KEY,
 `CUS_NAME` VARCHAR(20) NOT NULL,
 `CUS_PHONE` VARCHAR(10) NOT NULL,
 `CUS_CITY` varchar(30) NOT NULL,
 `CUS_GENDER` CHAR);


#category table
CREATE TABLE IF NOT EXISTS `category` (
 `CAT_ID` INT NOT NULL PRIMARY KEY,
 `CAT_NAME` VARCHAR(20) NOT NULL
);


#product table
CREATE TABLE IF NOT EXISTS `product` (
 `PRO_ID` INT NOT NULL PRIMARY KEY,
 `PRO_NAME` VARCHAR(20) NOT NULL DEFAULT "Dummy Product",
 `PRO_DESC` VARCHAR(60),
 `CAT_ID` INT NOT NULL,
 FOREIGN KEY (`CAT_ID`) REFERENCES CATEGORY (`CAT_ID`)
 );
 

#suppler pricing
CREATE TABLE IF NOT EXISTS `supplier_pricing` (
 `PRICING_ID` INT NOT NULL primary key,
 `PRO_ID` INT NOT NULL,
 `SUPP_ID` INT NOT NULL,
 `SUPP_PRICE` INT DEFAULT 0,
 FOREIGN KEY (`PRO_ID`) REFERENCES PRODUCT (`PRO_ID`),
 FOREIGN KEY (`SUPP_ID`) REFERENCES SUPPLIER(`SUPP_ID`)
 );


#order table
CREATE TABLE IF NOT EXISTS `order` (
 `ORD_ID` INT NOT NULL PRIMARY KEY,
 `ORD_AMOUNT` INT NOT NULL,
 `ORD_DATE` DATE,
 `CUS_ID` INT NOT NULL,
 `PRICING_ID` INT NOT NULL,
 FOREIGN KEY (`CUS_ID`) REFERENCES CUSTOMER(`CUS_ID`),
 FOREIGN KEY (`PRICING_ID`) REFERENCES SUPPLIER_PRICING(`PRICING_ID`)
 );


#rating table
CREATE TABLE IF NOT EXISTS `rating` (
 `RAT_ID` INT NOT NULL PRIMARY KEY,
 `ORD_ID` INT NOT NULL,
 `RAT_RATSTARS` INT NOT NULL,
 FOREIGN KEY (`ORD_ID`) REFERENCES `ORDER` (`ORD_ID`)
 );
